### ISSUE TITLE
Issue with coverage==5.0

### ISSUE THREAD

**Issue by ghackebeil** [bccp/runtests#24]
MPI tests with coverage end with a failure like the following:
```bash
================= 156 passed, 36 skipped, 4 warnings in 46.93s =================
Fatal Error on Rank 0
Traceback (most recent call last):
  File "~python3.7/lib/python3.7/site-packages/runtests/mpi/tester.py", line 333, in main
    code = self._test(config, comm=self.comm, **covargs)
  File "~/python3.7/lib/python3.7/site-packages/runtests/tester.py", line 275, in _test
    return config.hook.pytest_cmdline_main(config=config)
  File "~/python3.7/lib/python3.7/site-packages/runtests/coverage.py", line 60, in __exit__
    self.cov.stop()
AttributeError: 'CoverageData' object has no attribute 'write_file'
--------------------------------------------------------------------
```

Issue goes away if I revert to coverage==4.5.4

**Comment by rainwoodman** [comment]
It looks like coverage=5.0 changed how the path to the coverage data is dictated -- instead of determining the file name at write, it must be determined when the coverage object is created.

We need to move some of the logic in __exit__ of coverage.py to __enter__. Probably shall always modify cov.config.data_file to a temporary location regardless of number of ranks, then in __exit__ depending on the number of ranks combine or rename the coverage result.

@nickhand, any comments on this approach?

**Comment by rainwoodman** [comment]
I think the issue has creepped into nbodykit main test suite.

https://travis-ci.org/bccp/nbodykit/jobs/631984492

We need to sort this out.

**Comment by nickhand** [comment]
@rainwoodman I can take a look this weekend and offer some comments

**Comment by rainwoodman** [comment]
Great!

**Comment by nickhand** [comment]
It looks `write_file()` as be re-named to `write()`. The fix might be as simple as checking to see which of those functions exists and calling the right one

**Comment by nickhand** [comment]
I think the rest of the logic still works. They changed the underlying data format from a JSON file to a SQLite database file, but the current logic doesn't depend on the storage format

**Comment by rainwoodman** [comment]
It does depend on how the storage logic is executed -- the storage containers are created before write occurs, thus we had to lift the file names to before cov.start().
